config/routes.rb
Rails.application.routes.draw do
  root to: 'appointments#index'

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :appointments
  resources :app_api

  get '/new_token', to: 'users#new_token', as: 'generate_token'
  get '/show_token', to: 'users#show_token', as: 'show_token'

  get '/request_remind/:id', to: 'appointments#request_remind' ,as: 'request_remind'
  post '/request_remind/:id', to: 'appointments#create_remind'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :sort_by_session, -> (session) { order(session['sort'].to_sym => session['index'].to_sym) unless (session.nil? or session['sort'].nil? or session['index'].nil?) }
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user

  validates_presence_of :title
  validates_presence_of :app_time

  paginates_per 10

  enum state: { pending: 0, confirmed: 3, canceled: 10 }

  scope :by_user, -> (user_id) {where(user_id: user_id)}
  scope :without_canceled, -> {where.not(state: :canceled)}
  scope :by_date, -> (date) {where("app_time >= ?", date.to_date.beginning_of_day)
                                 .where("app_time <= ?", date.to_date.end_of_day)}
  scope :select_confirmed_near_hour, -> (datetime) {
                              where("app_time >= ?", datetime - 1.hours)
                              .where("app_time <= ?", datetime + 1.hours)
                              .where(state: :confirmed) }

  def author_of?(obj)
    self&.id == obj&.user_id
  end
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :recoverable, :rememberable
  devise :database_authenticatable, :registerable, :validatable

  validates :email, presence: true, uniqueness: true

  has_many :appointments, dependent: :delete_all

end

app/controllers/app_api_controller.rb
class AppApiController < ApplicationController
  before_action :set_variable

  def index
    if @user.present?
      save_log(@user)
      appointments = Appointment.by_user(@user.id).where(state: :confirmed)
      appointments = appointments.by_date(params[:date]) if params[:date].present?
      @response = appointments.to_json
    end
  end

  def new
    if @user.present?
      title, body, app_time = params[:title], params[:body], params[:app_time]
      if title.present? && body.present? && app_time.present?
        appointment = Appointment.new(
                        title: title,
                        body: body,
                        app_time: app_time,
                        state: 0,
                        user_id: @user.id)
        @response = appointment.to_json if appointment.save
        save_log(@user, appointment.id)
      end
    end
  end

  private

  def set_variable
    @response = false
    @user = User.find_by(guest_token: params[:token])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do
    redirect_to root_url, alert: t('not_have_access')
  end

  private

  def update_sort(name)
    session[name] = {} if session[name].nil?
    if params['sort'] != session[name]['sort']
      session[name] = {}
      session[name]['sort']  = params['sort'].to_sym
      session[name]['index'] = 'asc'
      return
    end
    session[name]['index'] = session[name]['index'] == 'asc' ? 'desc' : 'asc'
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, :notice => t('not_authenticate')
    end
  end

  def save_log(user, note = nil)
    log = Log.new(user_id: user.id, tcontroller: controller_name, taction: action_name, note: note)
    log.save
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_appointments, except: [ :new, :create ]
  before_action :check_access, except: [ :index, :new, :create ]

  def index
    update_sort(controller_name) if params['sort'].present?
    appointments = @appointments.without_canceled.sort_by_session(session[controller_name])
    @page = params[:page]
    @appointments = appointments.page(@page)
    authorize @appointments
  end

  def new
    @appointment = Appointment.new
    @appointment.app_time = Time.now + 2.hour + Time.zone_offset(Time.now.zone)
  end

  def create
    @appointment = Appointment.new(appointments_params)
    @appointment.user_id = current_user.id
    @appointment.state = 0
    if @appointment.save
      redirect_to appointments_path
    else
      flash[:danger] = @appointment.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def request_remind
    authorize @appointment
  end

  def create_remind
    authorize @appointment
    _perform_at = appointment.app_time - params[:app_time][:hours].to_i.hours
    AppointmentWorker.perform_at(_perform_at, appointment.id, current_user.email)

    redirect_to appointments_path
  end

  def update
    authorize @appointment
    if @appointments.select_confirmed_near_hour(@appointment.app_time).count == 0
      @appointment.state = :confirmed
      @appointment.save
      flash[:notice] = t('.confirmed')
    else
      flash[:danger] = t('.time_is_busy')
    end
    redirect_to appointments_path
  end

  def destroy
    authorize @appointment
    @appointment.state = :canceled
    @appointment.save
    redirect_to appointments_path
  end

  private

  def appointments_params
    params.require(:appointment).permit( :title, :body, :app_time )
  end

  def set_appointments
    @appointments = policy_scope(Appointment)
  end

  def check_access
    @appointment = @appointments.find_by(id: params[:id])
    redirect_to appointments_path, danger: t('access_denied!') unless @appointment.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show_token
    @title = t('.title_show_token')
    @api_token = current_user.guest_token
  end

  def new_token
    @title = t('.title_new_token')
    @api_token = SecureRandom.urlsafe_base64(nil, false)
    user = current_user
    user.guest_token = @api_token
    user.save
  end
end

app/helpers/app_api_helper.rb
module AppApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_KEYS = { success: 'alert-success',
                           error:   'alert-danger',
                           danger:  'alert-danger',
                           alert:   'alert-warning',
                           notice:  'alert-info'
  }.freeze

  def bootstrap_class_for flash_type
    BOOTSTRAP_FLASH_KEYS[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      unless !message
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
          concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
          concat message
        end)
      end
    end
    nil
  end

  def link_to_sort(sort, page = nil)
    class_name = 'glyphicon-title glyphicon'
    if sort.to_sym == session.try(:[], controller_name).try(:[], 'sort').try(:to_sym)
      if session.try(:[], controller_name).try(:[], 'index') == 'asc'
        class_name += ' glyphicon-sort-by-attributes'
      else
        class_name += ' glyphicon-sort-by-attributes-alt'
      end
    else
      class_name += ' glyphicon-sort'
    end
    if page.nil?
      content_tag :a, '', class: class_name, href: "#{controller_name}?sort=#{sort}", :'data-remote' => true
    else
      content_tag :a, '', class: class_name, href: "#{controller_name}?sort=#{sort}&page=#{page}", :'data-remote' => true
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/app_api/index.html.erb
<%= @response %>

app/views/app_api/index.js.erb
<%= @response %>

app/views/app_api/new.html.erb
<%= @response %>

app/views/app_api/new.js.erb
<%= @response %>

app/views/appointments/_appointment.html.haml
%tr
  %td
    = appointment.title
  %td
    = appointment.body
  %td
    = appointment.app_time
  %td
    = link_to '', appointment_path(appointment), class: 'glyphicon glyphicon-ok', title: t('.success'),method: :put, data: { confirm: t('.update?') } if policy(appointment).update?
    = link_to '', appointment_path(appointment), class: 'glyphicon glyphicon-remove', title: t('.cancel'), method: :delete, data: { confirm: t('.cancel?') } if policy(appointment).destroy?
    = link_to '', request_remind_path(appointment), class: 'glyphicon glyphicon-flag', title: t('.remind'), method: :get, 'data-remote': true if policy(appointment).request_remind?

app/views/appointments/_appointment_request_remind.html.haml
%div.modal-header
  %h5.modal-title#myModalLabel
    = t('.request_remind')
    %button.close{ type: 'button', 'data-dismiss': 'modal' }
      %span{ 'aria-hidden': 'true' }
        ×

%div.modal-body
  = form_for '', html: { class: 'form-horizontal', role: 'form' } do
    %div.form-group
      = label_tag :app_time, t('.app_time'), { class: 'col-sm-4 control-label' }
      %div.col-sm-8
        = number_field :app_time, 'hours'
    %div.form-group
      %label.col-sm-4
      %div.col-sm-8
        = submit_tag t('.submit'), :class => "btn"


%div.modal-footer
  %button.btn.btn-secondary{ type: 'button', 'data-dismiss': 'modal' }
    Close

app/views/appointments/_errors.html.haml
- if @appointment.errors.any?
  %div.form-group
    %label.col-sm-4
    %div.col-sm-8
      %div#error_explanation
        %ul
          - @appointment.errors.full_messages.each do |message|
            %li
              = message

app/views/appointments/_form.html.haml
= form_for @appointment, html: { class: 'form-horizontal', role: 'form' } do |app|
  %div.form-group
    %label.col-sm-4
    %div.col-sm-8
      = render 'appointments/errors'
  %div.form-group
    = app.label :title, t('.title'), { class: 'col-sm-4 control-label' }
    %div.col-sm-8
      = app.text_field :title, :class => "form-control", :id => "appointment_title", :type => "groupname"
  %div.form-group
    = app.label :body, t('.body'), { class: 'col-sm-4 control-label' }
    %div.col-sm-8
      = app.text_area :body, :class => "form-control", :id => "appointment_body", :type => "groupname"
  -#%div.form-group
  -#  = app.label :state, t('.state'), { class: 'col-sm-4 control-label' }
  -#  %div.col-sm-8
  -#    = app.select :state, Appointment.states.keys, { include_blank: false, hide_label: true, :selected => @appointment.state }, {:class => "form-control"}
  %div.form-group
    = app.label :app_time, t('.app_time'), { class: 'col-sm-4 control-label' }
    %div.col-sm-8
      = app.datetime_field :app_time, :class => "form-control", :id => "appointment_app_time"
  %div.form-group
    %label.col-sm-4
    %div.col-sm-8
      = app.submit

app/views/appointments/_table.html.haml
%thead
  %tr
    %th
      = link_to_sort('title', @page)
      = t('.title')
    %th
      = link_to_sort('body', @page)
      = t('.body')
    %th
      = link_to_sort('app_time', @page)
      = t('.app_time')
    %th

  %tbody
    = render @appointments

app/views/appointments/index.html.haml
%div.row
  %div.col-md-12
    %table.table.table-striped.appointments-table
      = render 'appointments/table'

= paginate @appointments, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-sm'

app/views/appointments/index.js.erb
$('.appointments-table').html("<%= escape_javascript render 'appointments/table' %>");

app/views/appointments/new.html.haml
= render 'appointments/form'

app/views/appointments/request_remind.js.erb
$('.modal-content').html("<%= escape_javascript render 'appointments/appointment_request_remind' %>")
$('#modal-container-5721').modal('show');

app/views/layouts/_alert.html.haml
= flash_messages

app/views/layouts/_menu.html.haml
%nav{ class: 'navbar navbar-default navbar-fixed-top', role: 'navigation' }
  %div{ class: 'navbar-header'}
    %button.some{ type: 'button', class: 'navbar-toggle', :'data-toggle' => 'collapse', :'data-target' => '#bs-example-navbar-collapse-1' }
      %span{ class: 'sr-only' } Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand.some{ href: root_path }
      %span.glyphicon.glyphicon-home

  %div{ class: 'collapse navbar-collapse', id: 'bs-example-navbar-collapse-1'}
    %ul.some{ class: 'nav navbar-nav'}
      - if user_signed_in? && controller_name == 'appointments' && action_name == 'index'
        %li
          = link_to t('.new_appointment'), new_appointment_path

    %ul{ class: 'nav navbar-nav navbar-right' }
      - if user_signed_in?
        %li.dropdown
          %a{ href: '#', class: 'dropdown-toggle', :'data-toggle' => 'dropdown' }
            = current_user.email
            %span.glyphicon.glyphicon-collapse-down
          %ul.dropdown-menu{"aria-labelledby": "navbarDropdownMenuLink"}
            %li
              = link_to t('Logout'), destroy_user_session_path, method: :delete
            - if current_user.guest_token.present?
              %li
                = link_to t('.show_token'), show_token_path, remote: true
            %li
              = link_to t('.new_token'), generate_token_path, remote: true
      - else
        %li
          = link_to t('Login'), new_user_session_path

app/views/layouts/_modal.html.haml
%div.modal.fade#modal-container-5721{ role: 'dialog', 'aria-labelledby': 'myModalLabel', 'aria-hidden': 'true' }
  %div.modal-dialog{ role: 'document' }
    %div.modal-content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Jruby20190201
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %div.container-fluid.main-frame
      = render 'layouts/menu'
      %div.col-md-12.alert-message
        = render 'layouts/alert'
      %div.col-md-12
        = yield
        = render 'layouts/modal'

app/views/users/_new_api.html.haml
%div.modal-header
  %h5.modal-title#myModalLabel
    = title
    %button.close{ type: 'button', 'data-dismiss': 'modal' }
      %span{ 'aria-hidden': 'true' }
        ×

%div.modal-body
  = api

%div.modal-footer
  %button.btn.btn-secondary{ type: 'button', 'data-dismiss': 'modal' }
    Close

app/views/users/new_token.js.erb
$('.modal-content').html("<%= escape_javascript render 'users/new_api', title: @title, api: @api_token %>")
$('#modal-container-5721').modal('show');

app/views/users/show_token.js.erb
$('.modal-content').html("<%= escape_javascript render 'users/new_api', title: @title, api: @api_token %>")
$('#modal-container-5721').modal('show');